[package]
name = "m-pdtsp"
version = "0.3.0"
edition = "2024"

[dependencies]
fixedbitset = "0.5.7"
clap = { version = "4.6.7", features = ["derive"] }
tikv-jemallocator = "0.7.0"
rpid = "0.4.0"
tsplib-parser = "0.1.0"
itertools = "0.15.0"
dypdl = "0.11.1"
dypdl-heuristic-search = "0.11.1"
io-util = { version = "0.3", path = "../io-util" }
